baseURL = 'https://staging.droughtland.com'
languageCode = 'en-us'
disableHugoGeneratorInject = true
title = 'Droughtland'

[params]
copyright = "Â© Copyright 2022 UNCCD"
metaDescription = "Droughtland Meta"
metaImage = ""
